mysite/urls.py
from django.conf.urls import *
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',

    (r'^$', include('zjblog.urls')),
    (r'^blogs/', include('zjblog.urls')),
    # Example:
    # (r'^mysite/', include('mysite.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),
    
    

)

zjblog/urls.py


from django.conf.urls import *
from zjblog.views import Details, Categorytoblogs, Blog_list, Tagtoblogs, showComments, weixin
from zjblog.feeds import LatestEntriesFeed
from zjblog.blogsitemap import BlogSitemap



sitemaps = { 'blog' : BlogSitemap }


    
    
urlpatterns = patterns('',
    #(r'^$', list_detail.object_list, category_info),
    (r'^$', Blog_list.as_view()),
    (r'^blog/(?P<pk>\d+)/$', Details.as_view()),
    (r'^category/(\d+)/$', Categorytoblogs.as_view()),
    (r'^latest/feed/$', LatestEntriesFeed()),
    (r'^tag/(?P<tag>[^/]+)/$', Tagtoblogs.as_view()),
    #(r'^tag/(?P<tag>\w+)/$', Tagtoblogs.as_view()),
    (r'^captcha/', include('captcha.urls')),
    (r'^postcomment/$', showComments),
    (r'^weixin/$', weixin),
    (r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps }),
    # Example:
    # (r'^mysite/', include('mysite.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    

    
)

zjblog/models.py
# -*- coding: utf-8 -*-

from django.db import models

from mptt.models import MPTTModel, TreeForeignKey
from taggit.managers import TaggableManager
import datetime

class Category(models.Model):
    title = models.CharField(u'分类', max_length=50)
    class Meta:
        verbose_name = u'分类'
        verbose_name_plural = u'分类'
        ordering = ['title']

    def get_absolute_url(self):
        return "/category/%i/" % self.id

    def __unicode__(self):
        return self.title

class FriendLink(models.Model):
    title = models.CharField(u'网站名称', max_length=50, help_text=u'给友情链接取一个名字')
    url =models.URLField(u'网站地址', help_text=u'友情链接的网址')
    class Meta:
        verbose_name = u'友情链接'
        verbose_name_plural = u'友情链接'
    
    def __unicode__(self):
        return self.title

class BaseInformation(models.Model):
    title = models.CharField(u'网站标题', max_length=100, help_text=u'浏览器顶部显示的内容')
    keywords = models.CharField(u'关键词', max_length=100, help_text=u'提供给搜索引擎的内容。关键词之间用英文逗号分隔')
    description = models.CharField(u'网站描述', max_length=100, help_text=u'提供给搜索引擎的内容。主要说明网站的用途')
    ico_url =models.URLField(u'图标地址', help_text=u'显示在浏览器地址栏中的图标的链接地址')
    log_url =models.URLField(u'logo地址', help_text=u'logo的链接地址')
    blog_name = models.CharField(u'博客名称', max_length=50)
    mark = models.CharField(u'个性签名', max_length=100)
    content = models.TextField(u'自我介绍')
    copyrightby = models.CharField(u'版权声明', max_length=100)
    my_template = models.CharField(u'当前所用主题', max_length=100)
    class Meta:
        verbose_name = u'网站基本设置'
        verbose_name_plural = u'网站基本设置'

    def __unicode__(self):
        return self.title
    

class Blog(models.Model):
    class Meta:
        verbose_name = u'日志'
        verbose_name_plural = u'日志'
        ordering = ['-pub_date']
        
    title = models.CharField(u'标题', max_length=50)
    describe = models.TextField(u'简介', blank=True)
    content = models.TextField(u'内容', help_text=u'上面填入详细内容')
    smallimage = models.URLField(u'配图', blank=True, help_text=u'配图的链接地址')
    pub_date = models.DateTimeField(u'写于', default=datetime.datetime.now)
    category =models.ForeignKey(Category, verbose_name=u'日志分类')
    #tag = TagField(u'标签', help_text=u'多个标签之间用空格分隔')
    tags = TaggableManager(u'标签', help_text=u'多个标签之间用英文逗号分隔')
    hotcount = models.IntegerField(u'热度', default=1, help_text=u'用于检索热门文章')
    commentcount = models.IntegerField(u'评论', default=0)
    def get_absolute_url(self):
        return "/blog/%i/" % self.id

    def __unicode__(self):
        return self.title

class ZComments(MPTTModel):
    r_blog = models.ForeignKey(Blog, verbose_name=u'评论的日志')
    c_author = models.CharField(u'评论者', max_length=60)
    e_mail = models.EmailField(u'邮箱')
    url = models.URLField(u'网址')
    content = models.TextField(u'内容')
    pub_date = models.DateTimeField(u'写于', default=datetime.datetime.now)
    parent = TreeForeignKey('self', null=True, blank=True, related_name='children')

    class Meta:
        verbose_name = u'评论'
        verbose_name_plural = u'评论'
        
    class MPTTMeta:
        
        order_insertion_by = ['pub_date']

        

zjblog/views.py
# -*- coding: utf-8 -*-

from django.core.context_processors import csrf
from django.shortcuts import render_to_response, render
from django.http import HttpResponse, HttpResponseRedirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic.list import ListView
from django.views.generic import DetailView
from zjblog.models import Blog, Category, FriendLink, BaseInformation, ZComments
from django.conf import settings
from django.contrib.sites.models import Site
#from django.contrib import comments
from captcha.fields import CaptchaField#m
from django.utils.encoding import smart_str, smart_unicode
from django.views.decorators.csrf import csrf_exempt
from django.core.urlresolvers import reverse
from django import forms #m
import xml.etree.ElementTree as ET
import random
import hashlib, re, time



class Blog_list(ListView):
        base_information = BaseInformation.objects.get(pk=1)
        queryset = Blog.objects.all()
        paginate_by = 5
        context_object_name = "blog_list"
        template_name = base_information.my_template+"/blog_list.html"

        def get_context_data(self, **kwargs):
                                
                allcomments = ZComments.objects.all()
                recent_comment = allcomments.order_by('-pub_date')[0:10]
                
                
                context = super(Blog_list, self).get_context_data(**kwargs)
                
                context['category_list'] = Category.objects.all()
                context['tag_list'] = Blog.tags.all()
                context['fls'] = FriendLink.objects.all()
                context['recent_comment'] = recent_comment
                context['base_information'] = self.base_information
                return context
                
class CommentsForm(forms.Form):#m
        
        author = forms.CharField(label=u'名称（必填）', required=True)
        e_mail = forms.EmailField(label=u'邮箱（必填）', required=True)
        url = forms.URLField(label=u'链接（可选）', required=False)
        commentbox = forms.CharField(label=u'内容（必填）', widget=forms.Textarea, required=True)        
        captcha = CaptchaField(label=u'验证码（必填）')

class Details(DetailView):
        context_object_name = 'post'
        base_information = BaseInformation.objects.get(pk=1)
        template_name = base_information.my_template+"/detail.html"
        form = CommentsForm()
        
        def get_queryset(self):
                return  Blog.objects.filter(pk = self.kwargs['pk'])
        def get_context_data(self, **kwargs):
             context = super(Details, self).get_context_data(**kwargs)
             blog = Blog.objects.get(pk = self.kwargs['pk'])
             #增加内容开始
             upid = 0
             nextid = 0
             upblog = ''
             nextblog = ''
             #增加内容结束
             
             post_tags = blog.tags.names()
             r_objects = blog.tags.similar_objects()
             blog.hotcount = blog.hotcount + 1
             blog.save()
             #增加内容开始
             lastpost = Blog.objects.latest('pub_date')
             if blog.id > 1 :
                     upid = blog.id - 1
                     upblog = Blog.objects.get(pk=upid)
             if blog.id < lastpost.id :
                     nextid = blog.id + 1
                     nextblog = Blog.objects.get(pk=nextid)
             #增加内容结束
             
             if len(r_objects) > 10:
                    r_objects = random.sample(r_objects, 10)
             context['category_list'] = Category.objects.all()
             #context['tag_list'] = Blog.tags.all()
             #context['fls'] = FriendLink.objects.all()
             nodes = ZComments.objects.filter(r_blog = blog)
             counts = 0
             for count in nodes:
                     counts = counts + 1
             blog.commentcount = counts
             blog.save()
             context['nodes'] = nodes
             context['similar'] = r_objects
             context['tags'] = post_tags
             context['base_information'] = self.base_information
             context['upid'] = upid
             context['nextid'] = nextid
             context['upblog'] = upblog
             context['nextblog'] = nextblog
             context['form'] = self.form
             return context         
    


class Categorytoblogs(ListView):
        base_information = BaseInformation.objects.get(pk=1)
        template_name = base_information.my_template+"/ctob.html"
        paginate_by = 5
        
        
        def get_queryset(self):
                
                c = Category.objects.get(pk=self.args[0])
                return Blog.objects.filter(category = c)

        def get_context_data(self, **kwargs):
                allcomments = ZComments.objects.all()
                recent_comment = allcomments.order_by('-pub_date')[0:10]
                
                context = super(Categorytoblogs, self).get_context_data(**kwargs)
                
                context['category_list'] = Category.objects.all()
                context['tag_list'] = Blog.tags.all()
                context['fls'] = FriendLink.objects.all()
                context['recent_comment'] = recent_comment
                context['cid'] = self.args[0]
                context['base_information'] = self.base_information
                return context        

class Tagtoblogs(ListView):
        base_information = BaseInformation.objects.get(pk=1)
        template_name = base_information.my_template+'/ttob.html'
        paginate_by = 5
        context_object_name = "blog_list"

        def get_queryset(self):
                return Blog.objects.filter(tags__name__in = [self.kwargs['tag']])

        def get_context_data(self, **kwargs):
                allcomments = ZComments.objects.all()
                recent_comment = allcomments.order_by('-pub_date')[0:10]
                
                context = super(Tagtoblogs, self).get_context_data(**kwargs)
                
                context['category_list'] = Category.objects.all()
                context['tag_list'] = Blog.tags.all()
                context['fls'] = FriendLink.objects.all()
                context['recent_comment'] = recent_comment
                context['blog_tag'] = self.kwargs['tag']
                context['base_information'] = self.base_information
                return context



def showComments(request):
        base_information = BaseInformation.objects.get(pk=1)
        template_name = base_information.my_template+"/test.html"
        if request.method == 'POST':
                form = CommentsForm(request.POST)
                pid = request.POST['parent_id']
                bid = request.POST['blog_id']
                if form.is_valid():
                        r_blog = Blog.objects.get(pk = request.POST['blog_id'])
                        if request.POST['parent_id'] != '':
                                r_comment = ZComments.objects.get(pk = request.POST['parent_id'])
                                r_comment.save()#这里一定要调用save方法，否则会出现"cannot assign instance is on database "default",value is on database "slave"的错误
                                comment = ZComments(r_blog = r_blog, c_author = request.POST['author'], e_mail = request.POST['e_mail'], url = request.POST['url'], content = request.POST['commentbox'], parent = r_comment)
                        else:
                                comment = ZComments(r_blog = r_blog, c_author = request.POST['author'], e_mail = request.POST['e_mail'], url = request.POST['url'], content = request.POST['commentbox'])
                        comment.save()
                
                        return HttpResponseRedirect('/blogs/blog/'+str(r_blog.id)+'/#c'+str(comment.id))
                #else:
                        #form = CommentsForm()
                return render(request, template_name, { 'form':form, 'blog_id':bid, 'parent_id':pid, })
                

#微信公众平台
@csrf_exempt
def weixin(request):
        
        if request.method =='GET':
                echostr = request.GET.get('echostr')
                boolvalue = checkSignature(request)
                if boolvalue:
                        return HttpResponse(echostr)
                
        if request.method == 'POST':
                response = HttpResponse(response_msg(request))
                return response
                
                #return HttpResponse('123')       
                        
                
        

def checkSignature(request):
        token = 'zzj'
        signature = request.GET.get('signature')
        timestamp = request.GET.get('timestamp')
        nonce = request.GET.get('nonce')
        

        tmpList = [token, timestamp, nonce]
        
        tmpList.sort()
        tmpstr = "%s%s%s" % tuple(tmpList)
        hashstr = hashlib.sha1(tmpstr).hexdigest()
        
        if hashstr == signature:
                return True
        else:
                return None

def parse_request_xml(rootElem):
        msg = {}
        if rootElem.tag == 'xml':
                for child in rootElem:
                        msg[child.tag] = smart_str(child.text)
        return msg

def response_msg(request):
        rawStr = smart_str(request.raw_post_data)
        msg = parse_request_xml(ET.fromstring(rawStr))
        msgType = msg.get("MsgType")
        msgContent = msg.get("Content")
        response_msg = u"您所发送的请求错误！"
        if msgType == "text":
                if msgContent == "r":
                        response_msg = u'<a href="http://zhangzhaojun.sinaapp.com">您好，点此阅读z系内容</a>'
                else:
                        response_msg = u"z系微信操作指南：\n\n发送字母r，进入浏览器阅读模式"
        if msgType == "event":

zjblog/templates/mobile/blog_list.html
<!DOCTYPE html>

{% load staticfiles %}
<html lang="zh-cn">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="{{base_information.description}}">
    <meta name="author" content="">
    <link rel="shortcut icon" href="{{base_information.ico_url}}">

    <title>{{base_information.title}}</title>

    <!-- Bootstrap core CSS -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'zjblog/mobile/style/blog.css' %}" rel="stylesheet">


    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  <style id="holderjs-style" type="text/css"></style></head>

  <body>

    <div class="blog-masthead">
      <div class="container">
        <nav class="blog-nav">
          <a class="blog-nav-item active" href="/">主页</a>{% for category in category_list %}
          <a class="blog-nav-item" href="blogs{{ category.get_absolute_url }}">{{ category.title }}</a>{% endfor %}
          
        </nav>
      </div>
    </div>

    <div class="container">

      <div class="blog-header">
      <img src="{% static 'zjblog/mobile/style/images/img03.gif' %}" class="img-responsive" style="float:left">
        <h1 class="blog-title">{{ base_information.blog_name }}</h1>
        <p class="lead blog-description">——{{ base_information.mark }}</p>
        
      </div>

      <div class="row">

        <div class="col-sm-8 blog-main">
{% for blog in blog_list %}
          <div class="blog-post">
            <h2 class="blog-post-title"><a href="blogs{{ blog.get_absolute_url }}">{{ blog.title }}</a></h2>
            <p class="blog-post-meta">{{ blog.pub_date|date:"Y年m月d日 D H:i" }}</p>

            <p>{{ blog.describe|safe }}</p>
            <a class="btn btn-default" href="blogs{{ blog.get_absolute_url }}" role="button">继续阅读({{ blog.hotcount }})</a>
            <a class="btn btn-default" href="blogs{{ blog.get_absolute_url }}#comments" role="button">评论({{ blog.commentcount }})</a>
          </div>
{% endfor %}
<!-- /.blog-post -->

          
<!--分页代码-->
<ul class="pager">
{% if is_paginated %}
<li><a href="/">首页</a></li>
    {% if page_obj.has_next %}
        {% if page_obj.has_previous %}
           <li><a href="/?page={{ page_obj.previous_page_number }}">上一页</a></li> 
           <li><a href="/?page={{ page_obj.next_page_number }}">下一页</a></li>
        {% else %}
        <li><a href="/?page={{ page_obj.next_page_number }}">下一页</a></li>
        {% endif %}
    {% else %}
        {% if page_obj.has_previous %}
        <li><a href="/?page={{ page_obj.previous_page_number }}">上一页</a></li>
        {% else %}
        {% endif %}
    {% endif %}
第{{ page_obj.number }}页，共{{ page_obj.paginator.num_pages }}页
{% else %}
{% endif %}
</ul>
<!--分页代码结束-->

        </div><!-- /.blog-main -->
        <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
          <div class="sidebar-module">
            <h4>关注博客</h4>
            <ol class="list-unstyled">
              <li>订阅我的博客：<a href="blogs/latest/feed/" target="_blank"><img src="{% static 'zjblog/mobile/style/images/rss.gif' %}" alt="订阅我的博客"></a></li>
              <li>关注新浪微博：<a href="http://weibo.com/u/1050994347" target="_blank"><img src="{% static 'zjblog/mobile/style/images/sub_sina.gif' %}" alt="关注新浪微博"></a></li>
              
            </ol>
          </div>

          <div class="sidebar-module sidebar-module-inset">
            <h4>标签云集</h4>
            <p>{% for tag in tag_list %}
               <a href="blogs/tag/{{tag}}">{{ tag }}</a>
               {% endfor %}</p>
          </div>
          <div class="sidebar-module">
            <h4>日志分类</h4>
            <ol class="list-unstyled">
            {% for category in category_list %}
              <li><a href="blogs{{category.get_absolute_url}}">{{category.title}}</a></li>
            {% endfor %}             
            </ol>
          </div>
          <div class="sidebar-module">
            <h4>网站链接</h4>
            <ol class="list-unstyled">
            {% for fl in fls %}
              <li><a href="{{ fl.url }}" target="_blank">{{ fl.title }}</a></li>
            {% endfor %}
            </ol>
          </div>
          <div class="sidebar-module">
            <h4>最新评论</h4>
            <ol class="list-unstyled">
            {% for rc in recent_comment %}
              <li><a href="blogs/blog/{{rc.r_blog.id}}/#c{{rc.id}}" target="_blank">{{rc.c_author}}：{{rc.content|slice:":20"}}</a></li>
            {% endfor %}
            </ol>
          </div>
        </div><!-- /.blog-sidebar -->

      </div><!-- /.row -->

    </div><!-- /.container -->

    <div class="blog-footer">
      <p>{{base_information.copyrightby}}. Powered by <a href="http://zhangzhaojun.sinaapp.com">zjblog</a>.</p>
      <p>
        <a href="/?page={{ page_obj.number }}">向上</a>
      </p>
    </div>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
    <script src="{% static 'zjblog/mobile/js/docs.min.js' %}"></script>
  

</body></html>

zjblog/templates/mobile/detail.html
<!DOCTYPE html>

{% load staticfiles %}
{% load gravatar %}
<html lang="zh-cn">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="{{base_information.description}}">
    <meta name="author" content="">
    <link rel="shortcut icon" href="{{base_information.ico_url}}">

    <title>{{ post.title }}|{{ base_information.title }}</title>

    <!-- Bootstrap core CSS -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'zjblog/mobile/style/blog.css' %}" rel="stylesheet">


    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  <style id="holderjs-style" type="text/css"></style>
<script type="text/javascript" src="{% static 'zjblog/mobile/js/jquery.min.js' %}"></script>
<script type="text/javascript">

$(document).ready(function(){
  $("[href='#tosomeone']").click(function(){
  var name=$(this).attr("name");
  var id=$(this).attr("id");
  $("#id_commentbox").val("对"+name+"说：");
  $("#parent_id").val(id);
  });

  $("#cancel").click(function(){
       
       $("#parent_id").val("");
  });
});

</script>


</head>

  <body>

    <div class="blog-masthead">
      <div class="container">
        <nav class="blog-nav">
          <a class="blog-nav-item active" href="/">主页</a>{% for hCategory in category_list %}
          <a class="blog-nav-item" href="../../../blogs{{ hCategory.get_absolute_url }}">{{ hCategory.title }}</a>{% endfor %}
          
        </nav>
      </div>
    </div>

    <div class="container">

      <div class="blog-header">
      <img src="{% static 'zjblog/mobile/style/images/img03.gif' %}" class="img-responsive" style="float:left">
        <h1 class="blog-title">{{ base_information.blog_name }}</h1>
        <p class="lead blog-description">——{{ base_information.mark }}</p>
        
      </div>

      <div class="row">

        <div class="col-sm-8 blog-main">

          <div class="blog-post">
            <h2 class="blog-post-title">{{ post.title }}</h2>
<p class="blog-post-meta">
<!--显示所属tags开始-->
标签：
{% for tag in tags %}
<a href="../../../blogs/tag/{{ tag }}" class="more">{{ tag }}</a>&nbsp;&nbsp 
{% endfor %}
<!--显示所属tags结束-->

<!--显示所属分类开始-->
分类：
<a href="../../../blogs{{post.category.get_absolute_url}}" class="more">{{ post.category }}</a>&nbsp;&nbsp 
<!--显示所属分类s结束--></p>

            

            <p>{{ post.content|safe }}</p>



<p class="blog-post-meta">{{ post.pub_date|date:"Y年m月d日 D H:i" }}</p>



<p>*** 转载请注明本文地址：<a href="../../../blogs{{ post.get_absolute_url }}" >http://zhangzhaojun.sinaapp.com/blogs{{ post.get_absolute_url }}</a> ***</p>
            <p>{% if upid != 0 %}上一篇：<a href="../../../blogs{{ upblog.get_absolute_url }}" >{{ upblog.title }}</a>{% endif %}<br />
                                {% if nextid != 0 %}下一篇：<a href="../../../blogs{{ nextblog.get_absolute_url }}" >{{ nextblog.title }}</a>{% endif %}</p>
          </div>

<!-- /.blog-post -->
<!-- JiaThis Button BEGIN -->
<div class="jiathis_style_32x32">
	<a class="jiathis_button_qzone"></a>
	<a class="jiathis_button_tsina"></a>
	<a class="jiathis_button_tqq"></a>
	<a class="jiathis_button_weixin"></a>
	<a class="jiathis_button_renren"></a>
	<a href="http://www.jiathis.com/share?uid=1911680" class="jiathis jiathis_txt jtico jtico_jiathis" target="_blank"></a>
</div>
<script type="text/javascript">
var jiathis_config = {data_track_clickback:'true'};
</script>
<script type="text/javascript" src="http://v3.jiathis.com/code/jia.js?uid=1396335698244324" charset="utf-8"></script>
<!-- JiaThis Button END -->

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

{% load mptt_tags %}
<!--显示树形评论--><br />

<a name="comments">&nbsp</a><p id="commentlist"><h3>评论列表：</h3></p>

<ul class="ulcomments">
    {% recursetree nodes %}
        <!--<li class="licomments">-->
    <div id="divcomments" >
            <div class="avatar">

            <a name="c{{node.id}}">&nbsp</a><IMG src="{% gravatar_url node.e_mail %}">
            </div>
            <div class="commentheader" style="word-wrap:break-word;white-space:normal;">
            {{ node.c_author }}：{{ node.content }}
            </div>
            <div class="commenttime">
            <span class="fc">{{ node.pub_date|date:"Y年m月d日 D H:i" }}</span>
            {% if node.get_level < 4 %}
            <a href="#tosomeone" name="{{ node.c_author }}" id="{{ node.id }}">回复</a>
             </div>
            {% endif %}


            {% if not node.is_leaf_node %}
                <ul class="children">
                    {{ children }}
                </ul>
            {% endif %}
     
         <!--</li>-->
     </div>
    {% endrecursetree %}

</ul>

<!--显示树形评论结束-->

<p id="tosomeone"><h2>发表评论：</h2></p><br />
<form action="../../../blogs/postcomment/" method="post">{% csrf_token %}
            {{ form.as_p }}

            <input type="hidden" name="blog_id" value="{{ post.id }}" />
            <input type="hidden" name="parent_id" id="parent_id" value="" /> {# <-- parent id goes here #}
            <input type="submit" value="发表评论" /><input type="reset" id="cancel" value="取消评论" /></p>
        </form>

        </div><!-- /.blog-main -->
        <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
          <div class="sidebar-module">
            <h4>关注博客</h4>
            <ol class="list-unstyled">
              <li>订阅我的博客：<a href="latest/feed/" target="_blank"><img src="{% static 'zjblog/mobile/style/images/rss.gif' %}" alt="订阅我的博客"></a></li>
              <li>关注新浪微博：<a href="http://weibo.com/u/1050994347" target="_blank"><img src="{%static 'zjblog/mobile/style/images/sub_sina.gif' %}" alt="关注新浪微博"></a></li>
              
            </ol>
          </div>

          
          <div class="sidebar-module">
            <h4>相关文章</h4>
            <ol class="list-unstyled">
            {% for article in similar %}
              <li><a href="../../../blogs{{article.get_absolute_url}}">{{ article.title }}</a></li>
            {% endfor %}             
            </ol>
          </div>
        </div><!-- /.blog-sidebar -->

      </div><!-- /.row -->

    </div><!-- /.container -->

    <div class="blog-footer">
      <p>{{base_information.copyrightby}}. Powered by <a href="http://zhangzhaojun.sinaapp.com">zjblog</a>.</p>
      <p>
        <a href="../../../blogs{{ post.get_absolute_url }}">向上</a>
      </p>
    </div>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
    <script src="{% static 'zjblog/mobile/js/docs.min.js' %}"></script>
  

</body></html>